# Generated by Django 2.1.5 on 2019-02-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='key', max_length=225, verbose_name='key')),
                ('value', models.CharField(help_text='value', max_length=225, verbose_name='value')),
            ],
            options={
                'verbose_name': 'Key Value Object',
                'verbose_name_plural': 'Key Value Objects',
            },
        ),
    ]
