# Generated by Django 2.1.5 on 2019-02-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyvalue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvalue',
            name='key',
            field=models.CharField(help_text='key', max_length=225, unique=True, verbose_name='key'),
        ),
    ]
